# -*- coding: utf-8 -*-
"""aerial cactus classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wLEciFm86wbOk2oI5Jhz6g2hK4exGqZK
"""

from fastai.vision import *
from fastai import *

from fastai.metrics import error_rate

# Commented out IPython magic to ensure Python compatibility.
#setting up our enviroment
# %reload_ext autoreload
# %autoreload 2
# %matplotlib inline

!unzip train.zip

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

!unzip test.zip

test_csv=pd.read_csv('sample_submission.csv')

test_csv.head()



path=Path('train')

path2=Path('test')

train_csv=pd.read_csv('train.csv')

test_images = ImageList.from_df(test_csv, path=path2)

np.random.seed(42)
data = (ImageList.from_df(train_csv,path=path)
        .split_by_rand_pct(0.01)
       
        .label_from_df()
         .add_test(test_images)
        .transform(get_transforms(flip_vert=True), size=128)
        .databunch(bs=16)).normalize(imagenet_stats)

data.show_batch(rows=3, figsize=(9,9))

learn = cnn_learner(data, models.resnet50, metrics=accuracy)

learn.fit_one_cycle(2,1e-02)

predictions, *_ = learn.get_preds(DatasetType.Test)

labels = np.argmax(predictions, 1)

sub_df = pd.DataFrame({
    'Id': test_csv.id,
    'has_cactus':labels
})
sub_df.to_csv('submission13.csv', index=False)

sub_df.head()

